version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: ims-backend
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=sqlite:///data/dev.sqlite3
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - backend_data:/app/data
    ports:
      - "4000:4000"
    depends_on: []

  frontend:
    build:
      context: ./frontend
    container_name: ims-frontend
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
  backend_data:


